spring:
  datasource:
    #url: jdbc:mysql://machintrack.cnr9boctdelw.us-east-1.rds.amazonaws.com:3306/machintrack
    url: jdbc:mysql://localhost:3306/machine_track
    #username: admin
    username: root
    #password: Uninorte2024
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG