server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    #url: jdbc:mysql://machintrack.cnr9boctdelw.us-east-1.rds.amazonaws.com:3306/machintrack
    url: jdbc:mysql://localhost:3306/machine_track
    #username: admin
    username: root
    #password: Uninorte2024
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
#    root: DEBUG
    org.springframework.security: DEBUG
    com.machine_track_app: DEBUG
